# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/ki18n': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/krunner': '@stable'
    'network/ktp-common-internals': '@same'
